[package]
name = "fellowship"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
solana-client = "1.18"
solana-sdk = "1.18"
anyhow = "1.0"
dotenvy = "0.15"
